language: ruby
rvm:
  - "1.9.3"
  - "1.9.2"
  - "2.0.0"
  - "2.0.1"
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-edge
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-head